# Generated by Django 4.2.27 on 2026-01-17 07:09

import apps.influencers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='English name', max_length=100)),
                ('name_th', models.CharField(help_text='Thai name', max_length=100)),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_th', models.CharField(help_text='Full name in Thai', max_length=100)),
                ('full_name_en', models.CharField(help_text='Full name in English', max_length=100)),
                ('phone', models.CharField(help_text='10-digit phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits starting with 0', regex='^0\\d{9}$')])),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('house_no', models.CharField(help_text='บ้านเลขที่', max_length=50)),
                ('village', models.CharField(blank=True, help_text='หมู่บ้าน/อาคาร', max_length=100)),
                ('moo', models.CharField(blank=True, help_text='หมู่ที่', max_length=20)),
                ('soi', models.CharField(blank=True, help_text='ซอย', max_length=100)),
                ('road', models.CharField(blank=True, help_text='ถนน', max_length=100)),
                ('sub_district', models.CharField(help_text='ตำบล/แขวง', max_length=100)),
                ('district', models.CharField(help_text='อำเภอ/เขต', max_length=100)),
                ('province', models.CharField(help_text='จังหวัด', max_length=100)),
                ('zipcode', models.CharField(help_text='รหัสไปรษณีย์', max_length=5)),
                ('allow_boost', models.BooleanField(default=False, help_text='Allow brands to boost posts')),
                ('boost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Boost price in THB', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('allow_original_file', models.BooleanField(default=False, help_text='Provide original/raw files')),
                ('original_file_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original file price in THB', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_card_front', models.ImageField(help_text='ID card front image', upload_to=apps.influencers.models.id_card_upload_path)),
                ('id_card_back', models.ImageField(help_text='ID card back image', upload_to=apps.influencers.models.id_card_upload_path)),
                ('bank_book', models.ImageField(help_text='Bank book first page', upload_to=apps.influencers.models.bank_book_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(help_text='Selected interest categories', related_name='influencers', to='influencers.interest')),
            ],
            options={
                'verbose_name': 'Influencer Profile',
                'verbose_name_plural': 'Influencer Profiles',
            },
        ),
    ]
