# Generated by Django 4.2.27 on 2026-01-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='id_card_back',
        ),
    ]
