# Generated by Django 4.2.27 on 2026-01-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_remove_influencerprofile_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='image',
            field=models.ImageField(blank=True, help_text='Creative background image', null=True, upload_to='interests/'),
        ),
    ]
