# Generated by Django 4.2.27 on 2026-01-21 05:54

import apps.influencers.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencers', '0004_interest_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencerprofile',
            options={'verbose_name': 'ข้อมูลอินฟลูเอนเซอร์', 'verbose_name_plural': 'ข้อมูลอินฟลูเอนเซอร์'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['order', 'name'], 'verbose_name': 'หมวดหมู่ความสนใจ', 'verbose_name_plural': 'หมวดหมู่ความสนใจ'},
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='allow_boost',
            field=models.BooleanField(default=False, help_text='Allow brands to boost posts', verbose_name='รับงาน Boost'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='allow_original_file',
            field=models.BooleanField(default=False, help_text='Provide original/raw files', verbose_name='ให้ไฟล์ต้นฉบับ'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bank_book',
            field=models.ImageField(help_text='Bank book first page', upload_to=apps.influencers.models.bank_book_upload_path, verbose_name='หน้าสมุดบัญชี'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='boost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Boost price in THB', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ราคา Boost'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='date_of_birth',
            field=models.DateField(help_text='Date of birth', verbose_name='วันเกิด'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='district',
            field=models.CharField(help_text='อำเภอ/เขต', max_length=100, verbose_name='อำเภอ/เขต'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='full_name_th',
            field=models.CharField(help_text='Full name in Thai', max_length=100, verbose_name='ชื่อ-นามสกุล (ไทย)'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='house_no',
            field=models.CharField(help_text='บ้านเลขที่', max_length=50, verbose_name='บ้านเลขที่'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='id_card_front',
            field=models.ImageField(help_text='ID card front image', upload_to=apps.influencers.models.id_card_upload_path, verbose_name='รูปบัตรประชาชน'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='interests',
            field=models.ManyToManyField(help_text='Selected interest categories', related_name='influencers', to='influencers.interest', verbose_name='ความสนใจ'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='moo',
            field=models.CharField(blank=True, help_text='หมู่ที่', max_length=20, verbose_name='หมู่ที่'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='original_file_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original file price in THB', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ราคาไฟล์ต้นฉบับ'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='phone',
            field=models.CharField(help_text='10-digit phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits starting with 0', regex='^0\\d{9}$')], verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='province',
            field=models.CharField(help_text='จังหวัด', max_length=100, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='road',
            field=models.CharField(blank=True, help_text='ถนน', max_length=100, verbose_name='ถนน'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='soi',
            field=models.CharField(blank=True, help_text='ซอย', max_length=100, verbose_name='ซอย'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='sub_district',
            field=models.CharField(help_text='ตำบล/แขวง', max_length=100, verbose_name='ตำบล/แขวง'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='village',
            field=models.CharField(blank=True, help_text='หมู่บ้าน/อาคาร', max_length=100, verbose_name='หมู่บ้าน/อาคาร'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='zipcode',
            field=models.CharField(help_text='รหัสไปรษณีย์', max_length=5, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='icon',
            field=models.CharField(help_text='Emoji icon', max_length=10, verbose_name='ไอคอน'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='image',
            field=models.ImageField(blank=True, help_text='Creative background image', null=True, upload_to='interests/', verbose_name='รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ใช้งาน'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(help_text='English name', max_length=100, verbose_name='ชื่อ (อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name_th',
            field=models.CharField(help_text='Thai name', max_length=100, verbose_name='ชื่อ (ไทย)'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ลำดับ'),
        ),
        migrations.CreateModel(
            name='SocialPlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('lemon8', 'Lemon8')], db_index=True, max_length=20, verbose_name='แพลตฟอร์ม')),
                ('platform_user_id', models.CharField(blank=True, help_text='Unique ID from platform', max_length=255, verbose_name='Platform User ID')),
                ('username', models.CharField(help_text='Display handle (e.g., @username)', max_length=255, verbose_name='ชื่อผู้ใช้')),
                ('profile_url', models.URLField(help_text='Link to the profile', max_length=500, verbose_name='ลิงก์โปรไฟล์')),
                ('profile_picture_url', models.URLField(blank=True, help_text='Profile picture URL', max_length=1000, verbose_name='รูปโปรไฟล์')),
                ('followers_count', models.PositiveIntegerField(default=0, help_text='Number of followers', verbose_name='ผู้ติดตาม')),
                ('following_count', models.PositiveIntegerField(blank=True, default=0, help_text='Number of following', verbose_name='กำลังติดตาม')),
                ('posts_count', models.PositiveIntegerField(blank=True, default=0, help_text='Number of posts/videos', verbose_name='โพสต์')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full API response for analysis', verbose_name='ข้อมูลดิบ')),
                ('is_verified', models.BooleanField(default=False, help_text='Platform verified badge', verbose_name='ยืนยันตัวตน')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='เชื่อมต่อเมื่อ')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='ซิงค์ล่าสุด')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'บัญชี Social Media',
                'verbose_name_plural': 'บัญชี Social Media',
                'ordering': ['platform'],
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
