# Generated by Django 4.2.27 on 2026-01-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_alter_influencerprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialplatformaccount',
            name='raw_data',
        ),
    ]
