# Generated by Django 4.2.27 on 2026-01-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_remove_socialplatformaccount_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='accept_affiliate',
            field=models.BooleanField(default=False, help_text='Willing to work on affiliate/commission basis', verbose_name='ยินดีรับงานแบบ Affiliate'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='accept_gifted_video',
            field=models.BooleanField(default=False, help_text='Willing to do video for high-value product without cash payment', verbose_name='ยินดีรับสินค้าเพื่อทำ Video (No Cash)'),
        ),
    ]
