# Generated by Django 4.2.27 on 2026-01-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_influencerprofile_accept_affiliate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อ-นามสกุล')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='Line ID')),
                ('tiktok_name', models.CharField(blank=True, max_length=255, verbose_name='TikTok Name')),
                ('tiktok_url', models.URLField(blank=True, max_length=500, verbose_name='TikTok URL')),
                ('reason', models.TextField(blank=True, default='ประวัติไม่ดีกับบริษัท (Blacklist)', verbose_name='เหตุผลที่ติดแบล็คลิสต์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่ม')),
            ],
            options={
                'verbose_name': 'คนติดแบล็คลิสต์',
                'verbose_name_plural': 'รายชื่อแบล็คลิสต์',
                'ordering': ['-created_at'],
            },
        ),
    ]
