# Generated by Django 6.0.1 on 2026-01-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0008_blacklistedinfluencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank Account Number', max_length=20, verbose_name='เลขที่บัญชี'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name (e.g. SCB, KBANK)', max_length=100, verbose_name='ชื่อธนาคาร'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='identification_number',
            field=models.CharField(blank=True, help_text='13-digit ID card number', max_length=13, verbose_name='เลขบัตรประจำตัวประชาชน'),
        ),
    ]
