# Generated by Django 4.2.27 on 2026-01-17 20:56

import apps.campaigns.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Campaign title', max_length=200)),
                ('description', models.TextField(help_text='Short description for card view')),
                ('full_description', models.TextField(blank=True, help_text='Full campaign brief and requirements')),
                ('brand_name', models.CharField(help_text='Brand/Company name', max_length=100)),
                ('brand_logo', models.ImageField(blank=True, help_text='Brand logo image', upload_to=apps.campaigns.models.brand_logo_upload_path)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget per person in THB', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('application_deadline', models.DateField(help_text='Last date to apply')),
                ('content_deadline', models.DateField(help_text='Content submission deadline')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Applications'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('requirements', models.JSONField(blank=True, default=dict, help_text='Campaign requirements (min followers, platforms, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for Approval'), ('APPROVED', 'Application Approved'), ('WORK_IN_PROGRESS', 'Working on Content'), ('SUBMITTED_SCRIPT', 'Script Submitted'), ('SCRIPT_APPROVED', 'Script Approved'), ('SUBMITTED_DRAFT', 'Draft Submitted'), ('DRAFT_APPROVED', 'Draft Approved'), ('SUBMITTED_FINAL', 'Final Submitted'), ('COMPLETED', 'Campaign Completed'), ('REJECTED', 'Rejected')], db_index=True, default='WAITING', max_length=30)),
                ('submission_data', models.JSONField(blank=True, default=dict, help_text='Submissions for each stage (script, draft, final)')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('application_note', models.TextField(blank=True, help_text='Note from influencer when applying')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Application',
                'verbose_name_plural': 'Campaign Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
