# Generated by Django 4.2.27 on 2026-01-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignapplication_payment_slip_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignapplication',
            name='payment_slip_url',
        ),
        migrations.AddField(
            model_name='campaignapplication',
            name='payment_slip',
            field=models.ImageField(blank=True, help_text='Payment slip image uploaded by admin', null=True, upload_to='payment_slips/'),
        ),
    ]
