# Generated by Django 4.2.27 on 2026-01-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaignapplication_payment_slip_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='draft_deadline',
            field=models.DateField(blank=True, help_text='Deadline for draft video submission', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='final_deadline',
            field=models.DateField(blank=True, help_text='Deadline for final work submission', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='script_deadline',
            field=models.DateField(blank=True, help_text='Deadline for script submission', null=True),
        ),
    ]
