# Generated by Django 4.2.27 on 2026-01-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_draft_deadline_campaign_final_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='followers_required',
            field=models.IntegerField(default=0, help_text='Minimum followers required'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, help_text='Campaign location (e.g. Bangkok, Online)', max_length=100),
        ),
    ]
