# Generated by Django 6.0.1 on 2026-01-20 06:00

import apps.campaigns.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_followers_required_campaign_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'แคมเปญ', 'verbose_name_plural': 'รายการแคมเปญ'},
        ),
        migrations.AlterModelOptions(
            name='campaignapplication',
            options={'ordering': ['-applied_at'], 'verbose_name': 'ใบสมัครแคมเปญ', 'verbose_name_plural': 'รายการใบสมัคร'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='application_deadline',
            field=models.DateField(help_text='Last date to apply', verbose_name='ปิดรับสมัคร'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brand_logo',
            field=models.ImageField(blank=True, help_text='Brand logo image', upload_to=apps.campaigns.models.brand_logo_upload_path, verbose_name='โลโก้แบรนด์'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='brand_name',
            field=models.CharField(help_text='Brand/Company name', max_length=100, verbose_name='ชื่อแบรนด์'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Budget per person in THB', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='งบประมาณ (บาท)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='content_deadline',
            field=models.DateField(help_text='Content submission deadline', verbose_name='กำหนดส่งงาน'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(help_text='Short description for card view', verbose_name='คำอธิบายอย่างย่อ'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='draft_deadline',
            field=models.DateField(blank=True, help_text='Deadline for draft video submission', null=True, verbose_name='กำหนดส่งดราฟท์'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='final_deadline',
            field=models.DateField(blank=True, help_text='Deadline for final work submission', null=True, verbose_name='กำหนดส่งไฟนอล'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='followers_required',
            field=models.IntegerField(default=0, help_text='Minimum followers required', verbose_name='ยอดผู้ติดตามขั้นต่ำ'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='full_description',
            field=models.TextField(blank=True, help_text='Full campaign brief and requirements', verbose_name='รายละเอียดทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, help_text='Campaign location (e.g. Bangkok, Online)', max_length=100, verbose_name='สถานที่'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Campaign requirements (min followers, platforms, etc.)', verbose_name='ข้อกำหนดเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='script_deadline',
            field=models.DateField(blank=True, help_text='Deadline for script submission', null=True, verbose_name='กำหนดส่งสคริปต์'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for Applications'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(help_text='Campaign title', max_length=200, verbose_name='ชื่อแคมเปญ'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from admin', verbose_name='โน้ตผู้ดูแล'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='application_note',
            field=models.TextField(blank=True, help_text='Note from influencer when applying', verbose_name='โน้ตจากผู้สมัคร'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สมัครเมื่อ'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='payment_slip',
            field=models.ImageField(blank=True, help_text='Payment slip image uploaded by admin', null=True, upload_to='payment_slips/', verbose_name='สลิปการโอนเงิน'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Approval'), ('APPROVED', 'Application Approved'), ('WORK_IN_PROGRESS', 'Working on Content'), ('SUBMITTED_SCRIPT', 'Script Submitted'), ('SCRIPT_APPROVED', 'Script Approved'), ('SUBMITTED_DRAFT', 'Draft Submitted'), ('DRAFT_APPROVED', 'Draft Approved'), ('SUBMITTED_FINAL', 'Final Submitted'), ('COMPLETED', 'Campaign Completed'), ('READY_TO_PAY', 'Ready to Pay'), ('PAYMENT_TRANSFERRED', 'Payment Transferred'), ('REJECTED', 'Rejected')], db_index=True, default='WAITING', max_length=30),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='submission_data',
            field=models.JSONField(blank=True, default=dict, help_text='Submissions for each stage (script, draft, final)', verbose_name='ข้อมูลการส่งงาน'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ'),
        ),
    ]
