# Generated by Django 4.2.27 on 2026-01-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignapplication',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Approval'), ('APPROVED', 'Application Approved'), ('WORK_IN_PROGRESS', 'Working on Content'), ('SUBMITTED_SCRIPT', 'Script Submitted'), ('SCRIPT_APPROVED', 'Script Approved'), ('SUBMITTED_DRAFT', 'Draft Submitted'), ('DRAFT_APPROVED', 'Draft Approved'), ('SUBMITTED_FINAL', 'Final Submitted'), ('COMPLETED', 'Campaign Completed'), ('PAYMENT_TRANSFERRED', 'Payment Transferred'), ('REJECTED', 'Rejected')], db_index=True, default='WAITING', max_length=30),
        ),
    ]
