# Generated by Django 4.2.27 on 2026-01-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaignapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='insight_deadline',
            field=models.DateField(blank=True, help_text='Deadline for insight submission', null=True, verbose_name='กำหนดส่ง Insight'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Approval'), ('APPROVED', 'Application Approved'), ('WORK_IN_PROGRESS', 'Working on Content'), ('SUBMITTED_SCRIPT', 'Script Submitted'), ('SCRIPT_APPROVED', 'Script Approved'), ('SUBMITTED_DRAFT', 'Draft Submitted'), ('DRAFT_APPROVED', 'Draft Approved'), ('SUBMITTED_FINAL', 'Final Submitted'), ('FINAL_APPROVED', 'Final Approved (Wait for Insight)'), ('SUBMITTED_INSIGHT', 'Insight Submitted'), ('INSIGHT_APPROVED', 'Insight Approved'), ('COMPLETED', 'Campaign Completed'), ('PAYMENT_TRANSFERRED', 'Payment Transferred'), ('REJECTED', 'Rejected')], db_index=True, default='WAITING', max_length=30),
        ),
    ]
