# Generated by Django 4.2.27 on 2026-01-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_insight_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brief_url',
            field=models.URLField(blank=True, help_text='Link to campaign brief/details (e.g. Google Doc, Canva)', max_length=500, null=True, verbose_name='ลิงก์รายละเอียดบรีฟงาน'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='followers_required',
            field=models.IntegerField(blank=True, default=0, help_text='Minimum followers required', null=True, verbose_name='ยอดผู้ติดตามขั้นต่ำ'),
        ),
    ]
