# Generated by Django 4.2.27 on 2026-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_brief_url_alter_campaign_followers_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='share_token',
            field=models.CharField(blank=True, help_text='Token for client sharing', max_length=100, null=True, unique=True, verbose_name='Share Token'),
        ),
    ]
