# Generated by Django 4.2.27 on 2026-01-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_campaign_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='show_slip_to_client',
            field=models.BooleanField(default=False, verbose_name='แสดงสลิปให้ลูกค้าเห็น'),
        ),
    ]
