# Generated by Django 4.2.27 on 2026-01-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_show_slip_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignapplication',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Approval'), ('APPROVED', 'Application Approved'), ('WORK_IN_PROGRESS', 'Working on Content'), ('SUBMITTED_SCRIPT', 'Script Submitted'), ('SCRIPT_APPROVED', 'Script Approved'), ('REVISE_SCRIPT', 'Revise Script'), ('SUBMITTED_DRAFT', 'Draft Submitted'), ('DRAFT_APPROVED', 'Draft Approved'), ('REVISE_DRAFT', 'Revise Draft'), ('SUBMITTED_FINAL', 'Final Submitted'), ('FINAL_APPROVED', 'Final Approved (Wait for Insight)'), ('REVISE_FINAL', 'Revise Final'), ('SUBMITTED_INSIGHT', 'Insight Submitted'), ('INSIGHT_APPROVED', 'Insight Approved'), ('COMPLETED', 'Campaign Completed'), ('PAYMENT_TRANSFERRED', 'Payment Transferred'), ('REJECTED', 'Rejected')], db_index=True, default='WAITING', max_length=30),
        ),
    ]
