# Generated by Django 4.2.27 on 2026-01-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_campaignapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='insight_feedback',
            field=models.TextField(blank=True, help_text='Admin feedback for insight', verbose_name='Feedback สำหรับ Insight'),
        ),
        migrations.AddField(
            model_name='campaignapplication',
            name='insight_image',
            field=models.URLField(blank=True, help_text='URL to insight screenshot', max_length=500, null=True, verbose_name='รูป Insight'),
        ),
        migrations.AddField(
            model_name='campaignapplication',
            name='insight_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When insight was last submitted', null=True, verbose_name='ส่ง Insight เมื่อ'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for Approval'), ('APPROVED', 'Application Approved'), ('WORK_IN_PROGRESS', 'Working on Content'), ('SUBMITTED_SCRIPT', 'Script Submitted'), ('SCRIPT_APPROVED', 'Script Approved'), ('REVISE_SCRIPT', 'Revise Script'), ('SUBMITTED_DRAFT', 'Draft Submitted'), ('DRAFT_APPROVED', 'Draft Approved'), ('REVISE_DRAFT', 'Revise Draft'), ('SUBMITTED_FINAL', 'Final Submitted'), ('FINAL_APPROVED', 'Final Approved (Wait for Insight)'), ('REVISE_FINAL', 'Revise Final'), ('SUBMITTED_INSIGHT', 'Insight Submitted'), ('REVISE_INSIGHT', 'Revise Insight'), ('INSIGHT_APPROVED', 'Insight Approved'), ('COMPLETED', 'Campaign Completed'), ('PAYMENT_TRANSFERRED', 'Payment Transferred'), ('REJECTED', 'Rejected')], db_index=True, default='WAITING', max_length=30),
        ),
    ]
