# Generated by Django 6.0.1 on 2026-01-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_alter_campaign_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='requirements',
            field=models.TextField(blank=True, help_text='Campaign requirements (min followers, platforms, etc.)', verbose_name='ข้อกำหนดเพิ่มเติม'),
        ),
    ]
