# Generated by Django 4.2.27 on 2026-01-26 03:36

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_alter_campaign_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Campaign cover image (displayed on dashboard)', null=True, upload_to=apps.campaigns.models.campaign_cover_upload_path, verbose_name='รูปปกแคมเปญ'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='payment_slip',
            field=models.ImageField(blank=True, help_text='Payment slip image uploaded by admin', null=True, upload_to=apps.campaigns.models.payment_slip_upload_path, verbose_name='สลิปการโอนเงิน'),
        ),
    ]
