# Generated by Django 4.2.27 on 2026-01-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campaign_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='brief_url',
            field=models.URLField(blank=True, help_text='Link to campaign brief/details (e.g. Google Doc, Canva)', max_length=2000, null=True, verbose_name='ลิงก์รายละเอียดบรีฟงาน'),
        ),
    ]
