# Generated by Django 4.2.27 on 2026-01-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_alter_campaign_brief_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AddField(
            model_name='campaignapplication',
            name='insight_data',
            field=models.JSONField(blank=True, default=dict, help_text='AI Analysis results (likes, comments, sentiment, etc.)', verbose_name='ข้อมูลวิเคราะห์ Insight'),
        ),
    ]
