# Generated by Django 4.2.27 on 2026-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='insight_files',
            field=models.JSONField(blank=True, default=list, help_text='List of insight screenshot URLs', verbose_name='รูป Insight (หลายรูป)'),
        ),
    ]
