# Generated by Django 4.2.27 on 2026-01-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_campaignapplication_insight_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInsightMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.BigIntegerField(default=0, help_text='Total views from all media')),
                ('total_likes', models.BigIntegerField(default=0, help_text='Total likes')),
                ('total_comments', models.BigIntegerField(default=0, help_text='Total comments')),
                ('total_shares', models.BigIntegerField(default=0, help_text='Total shares/saves')),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Engagement Rate % ((Likes+Comments+Shares)/Views * 100)', max_digits=10)),
                ('cost_per_view', models.DecimalField(decimal_places=4, default=0.0, help_text='Cost Per View (Budget / Total Views)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight_metric', to='campaigns.campaignapplication')),
            ],
        ),
    ]
