# Generated by Django 4.2.27 on 2026-01-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_campaigninsightmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignapplication',
            name='insight_note',
            field=models.TextField(blank=True, help_text='Note from influencer when submitting insight', verbose_name='โน้ตการส่ง Insight'),
        ),
    ]
