# Generated by Django 4.2.27 on 2026-01-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'ผู้ใช้งาน', 'verbose_name_plural': 'ผู้ใช้งานทั้งหมด'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สมัคร'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name from LINE profile', max_length=100, verbose_name='ชื่อที่แสดง'),
        ),
        migrations.AlterField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(db_index=True, help_text='Unique identifier from LINE', max_length=50, unique=True, verbose_name='LINE User ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from LINE', max_length=1000, verbose_name='รูปโปรไฟล์'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)', verbose_name='เหตุผลที่ปฏิเสธ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='NEW', help_text='User approval status', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด'),
        ),
    ]
