# Generated by Django 6.0.1 on 2026-01-23 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve_user', 'Approve User User'), ('reject_user', 'Reject User'), ('create_campaign', 'Create Campaign'), ('edit_campaign', 'Edit Campaign'), ('approve_work', 'Approve Work'), ('reject_work', 'Reject Work'), ('comment_user', 'Comment on User'), ('other', 'Other')], max_length=50)),
                ('target_model', models.CharField(help_text='Model name e.g. User, Campaign', max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_str', models.CharField(help_text='String representation of the target', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='Performed by')),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
