# Generated by Django 6.0.1 on 2026-01-20 06:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0006_alter_campaign_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='รหัสธุรกรรม')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='จำนวนเงิน')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'ฝากเงิน'), ('PAYOUT', 'จ่ายเงิน Influencer'), ('SERVICE_FEE', 'ค่าคอมมิชชั่น Platform'), ('VAT', 'ภาษีมูลค่าเพิ่ม'), ('WITHDRAWAL', 'ถอนเงิน'), ('REFUND', 'คืนเงิน')], db_index=True, max_length=20, verbose_name='ประเภท')),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('COMPLETED', 'สำเร็จ'), ('FAILED', 'ล้มเหลว')], db_index=True, default='PENDING', max_length=20, verbose_name='สถานะ')),
                ('reference_note', models.CharField(blank=True, help_text='เลขที่สลิป หรือ Reference ID จากธนาคาร', max_length=255, verbose_name='หมายเลขอ้างอิง')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='วันที่ทำรายการ')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='campaigns.campaignapplication', verbose_name='งาน')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับ')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จ่าย')),
            ],
            options={
                'verbose_name': 'ธุรกรรม',
                'verbose_name_plural': 'รายการธุรกรรม',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='ราคางานเต็มก่อนหักค่าบริการ', max_digits=18, verbose_name='มูลค่างานรวม')),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='ค่าคอมมิชชั่น 10% ของมูลค่างาน', max_digits=18, verbose_name='ค่าบริการ Platform (10%)')),
                ('net_payout', models.DecimalField(decimal_places=2, help_text='ยอดสุทธิที่ Influencer ได้รับ (90%)', max_digits=18, verbose_name='ยอดจ่าย Influencer')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='7% ของค่าบริการ (ถ้ามี)', max_digits=18, verbose_name='ภาษีมูลค่าเพิ่ม (VAT)')),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ภาษีหัก ณ ที่จ่าย 3% (ถ้ามี)', max_digits=18, verbose_name='ภาษีหัก ณ ที่จ่าย')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_records', to='campaigns.campaignapplication', verbose_name='งาน')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_record', to='finance.transaction', verbose_name='ธุรกรรมอ้างอิง')),
            ],
            options={
                'verbose_name': 'รายได้ Platform',
                'verbose_name_plural': 'รายได้ Platform ทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ยอดเงินปัจจุบันในกระเป๋า (ห้ามติดลบ)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ยอดเงินคงเหลือ')),
                ('status', models.CharField(choices=[('ACTIVE', 'ใช้งานปกติ'), ('FROZEN', 'ถูกระงับ')], default='ACTIVE', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตเมื่อ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'กระเป๋าเงิน',
                'verbose_name_plural': 'กระเป๋าเงินทั้งหมด',
            },
        ),
    ]
