# Generated by Django 4.2.27 on 2026-01-20 06:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        # migrations.AddConstraint(
        #     model_name='wallet',
        #     constraint=models.CheckConstraint(check=models.Q(('balance__gte', Decimal('0.00'))), name='wallet_balance_non_negative'),
        # ),
    ]
