# Generated by Django 4.2.27 on 2026-01-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_wallet_wallet_balance_non_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformrevenue',
            name='net_payout',
            field=models.DecimalField(decimal_places=2, help_text='Full payment to influencer (no deduction)', max_digits=18, verbose_name='ยอดจ่าย Influencer'),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, help_text='Agency fee for internal tracking - NOT deducted from influencer', max_digits=18, verbose_name='Agency Fee (Internal)'),
        ),
    ]
