# Generated by Django 4.2.27 on 2026-01-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_platformrevenue_net_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrevenue',
            name='settlement_status',
            field=models.CharField(choices=[('UNCLAIMED', 'ยังไม่เบิกจ่าย'), ('PENDING', 'รออนุมัติ'), ('SETTLED', 'เบิกจ่ายแล้ว')], default='UNCLAIMED', max_length=20, verbose_name='สถานะการเบิกจ่าย'),
        ),
    ]
