# Generated by Django 4.2.27 on 2026-01-23 06:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_platformrevenue_settlement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformrevenue',
            name='settlement_status',
            field=models.CharField(choices=[('UNCLAIMED', 'รอการชำระ'), ('PENDING', 'กำลังดำเนินการ'), ('SETTLED', 'ชำระแล้ว')], db_index=True, default='UNCLAIMED', max_length=20, verbose_name='สถานะการชำระบัญชี'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='รหัสการชำระเงิน')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='ยอดรวมที่ชำระ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ทำรายการ')),
            ],
            options={
                'verbose_name': 'การชำระบัญชีรายได้',
                'verbose_name_plural': 'รายการชำระบัญชีรายได้',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='platformrevenue',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='finance.settlement', verbose_name='รายการชำระบัญชี'),
        ),
    ]
