# Generated by Django 6.0.1 on 2026-01-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_platformrevenue_settlement_status_settlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='revenue_settlements/', verbose_name='หลักฐานการโอน'),
        ),
    ]
