# Generated by Django 4.2.27 on 2026-01-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='topic',
            field=models.CharField(choices=[('BUG', 'Bug Report'), ('PAYMENT', 'Payment Issue'), ('ACCOUNT', 'Account Settings'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
