# Generated by Django 4.2.27 on 2026-01-21 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_alter_supportticket_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'ตั๋วแจ้งปัญหา', 'verbose_name_plural': 'รายการแจ้งปัญหา'},
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='github_issue_url',
            field=models.URLField(blank=True, help_text='Link to the GitHub Issue', null=True, verbose_name='ลิงก์ GitHub Issue'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='เรื่อง'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='topic',
            field=models.CharField(choices=[('BUG', 'Bug Report'), ('PAYMENT', 'Payment Issue'), ('ACCOUNT', 'Account Settings'), ('OTHER', 'Other')], max_length=20, verbose_name='หัวข้อ'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขเมื่อ'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ร้องเรียน'),
        ),
    ]
