# Generated by Django 4.2.27 on 2026-01-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='ไฟล์แนบ'),
        ),
    ]
